version: "3"

services:
  node:
    image: node:16.15.1-bullseye
    container_name: node
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8880:3000
    working_dir: /usr/src/app
